name = "cyrus-proxy"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# KV namespaces
[[kv_namespaces]]
binding = "OAUTH_TOKENS"
id = "3f479deaed5c48cd9155fb799dd93c14"
preview_id = "oauth_tokens_preview"

[[kv_namespaces]]
binding = "OAUTH_STATE"
id = "8b994bfaf3754baab6412686666fdf3c"
preview_id = "oauth_state_preview"

[[kv_namespaces]]
binding = "EDGE_TOKENS"
id = "e780a2273a7348e5ac27b33dfea4cb1f"
preview_id = "edge_tokens_preview"

[[kv_namespaces]]
binding = "WORKSPACE_METADATA"
id = "0295b62cf81848228d1baf9df9281218"
preview_id = "workspace_metadata_preview"

# Environment variables (use wrangler secret for production)
[vars]
OAUTH_REDIRECT_URI = "https://cyrus-proxy.ceedar.workers.dev/oauth/callback"

# Durable Objects removed - using webhook-only architecture
# Migrations commented out for local development
# [[migrations]]
# tag = "v2"
# deleted_classes = ["EventStreamDurableObject"]

# Local development settings
[miniflare]
kv_persist = true